/*
 * Chomp Food Database API Documentation
 *
 * ## Important An **[API key](https://chompthis.com/api/)** is required for access to this API. Get yours at **[https://chompthis.com/api](https://chompthis.com/api/)**.  ### Getting Started   * **[Subscribe](https://chompthis.com/api/#pricing)** to the API.   * Scroll down and click the \"**Authorize**\" button.   * Enter your API key into the \"**value**\" input, click the \"**Authorize**\" button, then click the \"**Close**\" button.   * Scroll down to the section titled \"**default**\" and click on the API endpoint you wish to use.   * Click the \"**Try it out**\" button.   * Enter the information the endpoint requires.   * Click the \"**Execute**\" button.  ### Example    * Branded food response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)**   * Ingredient response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)**  ### How Do I Find My API Key?   * Your API key was sent to the email address you used to create your subscription.   * You will also find your API key in the **[Client Center](https://chompthis.com/api/manage.php)**.   * Read **[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)** for more information.  ||| | ------- | -------- | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | | 
 *
 * API version: 1.0.0-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An object containing information for this specific item.
type IngredientObjectItems struct {
	// Item name as provided by brand owner or as shown on packaging
	Name string `json:"name,omitempty"`

	Categories []string `json:"categories,omitempty"`
	// An array containing nutrient informatio objects for this food item
	Nutrients []IngredientObjectNutrients `json:"nutrients,omitempty"`

	CalorieConversionFactor *IngredientObjectCalorieConversionFactor `json:"calorie_conversion_factor,omitempty"`
	// The multiplication factor used to calculate protein from nitrogen
	ProteinConversionFactor *BigDecimal `json:"protein_conversion_factor,omitempty"`

	DietLabels *BrandedFoodObjectDietLabels `json:"diet_labels,omitempty"`
	// An array of objects containing the constituent parts of a food (e.g. bone is a component of meat)
	Components []IngredientObjectComponents `json:"components,omitempty"`
	// An array of objects containing information on discrete amounts of a food found in this item
	Portions []IngredientObjectPortions `json:"portions,omitempty"`
	// Common names associated with this item. These generally clarify what the item is (e.g. when the brand name is \"BRAND's Spicy Enchilada\" the common name may be \"Chicken enchilada\")
	CommonNames string `json:"common_names,omitempty"`
	// A description of this item
	Description string `json:"description,omitempty"`
	// Comments on any unusual aspects of this item. Examples might include unusual aspects of the food overall.
	Footnote string `json:"footnote,omitempty"`
}
